### ISSUE TITLE
why is time_emb added to the second dimension rather than the last dimension of the x?

### ISSUE THREAD

**Issue by hao-zheng-uoa** [Finspire13/DiffAct#8]
Thank you for sharing this work. 

I got a question that I wish I can get your answer.
In MixedConvAttModule and MixedConvAttModuleV2, why would you add the time_embed to the second dimension, the feature dimension, rather than the last dimension, the last dimension?

Thank you in advance.

**Comment by Finspire13** [comment]
I am not sure whether I get your question correctly. I guess it is because the 'time' in time_embed means the 'time step' in the diffusion process (i.e., noise level), instead of the 'frame' on the video timeline. So, it follows the practice in diffusion model to add time embedding as some features.

**Comment by hao-zheng-uoa** [comment]
> I am not sure whether I get your question correctly. I guess it is because the 'time' in time_embed means the 'time step' in the diffusion process (i.e., noise level), instead of the 'frame' on the video timeline. So, it follows the practice in diffusion model to add time embedding as some features.

Ohh, I SEE. Thank you for your prompt reply.
